{% set name = "jeepney" %}
{% set version = "0.4" %}
{% set sha256 = "6089412a5de162c04747f0220f6b2223b8ba660acd041e52a76426ca550e3c70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: FLIT_ROOT_INSTALL=1 flit install --deps none  # [not win]
  script: flit install --deps none  # [win]

requirements:
  build:
    - python >=3.5
    - flit
  run:
    - python >=3.5

test:
  imports:
    - jeepney

about:
  home: https://gitlab.com/takluyver/jeepney
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pure Python DBus interface'
  description: |
    This is a low-level, pure Python DBus protocol client. It has
    an I/O-free core, and integration modules for different event
    loops.
  doc_url: https://jeepney.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/takluyver/jeepney

extra:
  recipe-maintainers:
    - ccordoba12
    - takluyver
