{% set name = "jeepney" %}
{% set version = "0.4.1" %}
{% set sha256 = "13806f91a96e9b2623fd2a81b950d763ee471454aafd9eb6d75dbe7afce428fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: FLIT_ROOT_INSTALL=1 flit install --deps none

requirements:
  host:
    - python >=3.5
    - flit
  run:
    - python >=3.5

test:
  imports:
    - jeepney

about:
  home: https://gitlab.com/takluyver/jeepney
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pure Python DBus interface'
  description: |
    This is a low-level, pure Python DBus protocol client. It has
    an I/O-free core, and integration modules for different event
    loops.
  doc_url: https://jeepney.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/takluyver/jeepney

extra:
  recipe-maintainers:
    - ccordoba12
    - takluyver
