travis:
  secure:
    BINSTAR_TOKEN: eVLvWsR0jrNrjPGuTFpjWlfJacB1kcyrHBATJKwegOFT811wLdL+dU+BdMa6bZvGw4PICRx2Ef4PtSuk/zTQz5GDeTtc1Sgg3t6PNxj+Z2jkGXSEzl9WZnYop77Jlgkz/zdJU8N39rqV4PAVGtEKubHKD4wxElxHutpSpQ6r4pOVjR9p6DaOjHTGZELKQrQi4PCSLoXSqxXEYsefdx7glUQc43nDip6uzckAMOYszhmNicdk4omitTBRWgSKvuTIR8kxqS7vIyLrqQXgB++/SuT+vuQCpaj12LgfySCCcEcTpMm/ghum79xjrNafHf5O9LoV6ElzvG/wROW3hpWUPar4x9K2mdyHT750t/maf3NYkhUc7gd36oZl0nDdMCYYB9VYv9PEod4G12XWN2ncE+aq3S4EIPdSUKsvwhkyfW4H94jNwgsvD5EYGAQpBf7GF6nBtUXvzi64V9ufl2ssMhFpbc+ET6TRLyWeppuT83hv2NkitRdybd7Aj83jm51L1E8xD3ybrXcrUq66T2apwabU3hKtlVMCXlpvlhUXMB/J0tVidzPCniqtjHLRtjQhSjdMAsyjiF9Ledo10cRLyJbDsy0ACEiF1VXnB3gF6n8vaIRmbrFE6XFBJuzwf0euD3EXU5HYw7jIQP6ahG9U0AHl/5fe0hJ3BIJ+qZsrxJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
