travis:
  secure:
    BINSTAR_TOKEN: A6uNr+U/9N+zKF8RMUDwqlHHngdUVCDmKGLdYK4s5eTOCgPYtrsxrSCnVWk0Mz1HE+i5gIB009Z8fCjL3m+aANouZClDd6B6QX/+1kelsFXiLUQtalDVdxRLtV+PvFxCVXIS2GJLd39K0fd2gspr7gxZKKettYb4shYFtu/AC9eoRKlOZ0iCO62mXEzYjB1Ef2bKmbZGPzhILWmeTszKcZwaDhyfDIqYMGH5wEGUlox20otVfpWVo2Alv/GOatPOCapys2yZZiaNH0K4/G7FbIKk9Y931e8pvNox5+q01tzJtghc0Miz8gAC2thoNDEewn17AUpMEVC+S3tlzo4YBEG9VrwaPaGJvusZR/lqT3CxpbX+OXwUUtUKDjQMMMi3gWXRvcsH2cUTp6ox3B3Lu5K0qx1+mhUoiKTNg6L8+ULxMNJncHiUpFC6PLGSglxk0+3knfCH8jLTFPmIjNtJJ4mwqXIL7gLU/cfYs/xFdaxi3PT4rZGh54PFXByxyPd2B5liQ6CUiijzQ4wgkvQr/uOhPmeqZUhjsQCukuK6v+oLoM6cOMPbPr0Qgo+cBTKPshs453I3meHbq9okGLRV8h4cZhKpMR0JsrXecbH5gPAk4DAw0ZjKPQKP3JkVPBm7uaBjUeWMtgLoxdV/pFmRKsY7g/2L7l54Cbm9XXrvuN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
