travis:
  secure:
    BINSTAR_TOKEN: E4UjF6PYJdlKDbxxuCyEngf+laE5z569VTQQd+v2fa1Ryqf87OpaqY4v+Yg+4dgNF8slKKsrWZrwGtk9dow3KU+j2lZ65o1emQLqfdufM7zmB0VLoL9lgHbavi+JNCj+ozMNKY338kbiVbw0fIPvSea+E7ubf/wkiEStmmz2dy9JqU/9Z+e1qcOm+H/o2HSswsrZM+Yn+jBGxB3SWYAFvCWZNezTx8+x6aF73iFYxKYoJp1Gpktzv2dqjr5MY/BC5ZVHLeSYVuPGZ3usQJwEXKm5qHVVPt2YkhDe4z72Ss5VtHIW9x+SrUziFzoqyFHQ8hiniLVx++QxOKG4PI6UwQFJ6T8whOhZ4J8yShU9qGYUQ6sv0QuHPqRPFpdmOmPm0+qUTY2iu4u1kQgMOdBh38pIIXvIcOdFmA9d3We0Gzi5li3UnGX6WzazmljKYQGZ3vCcVUVu0011b1Cqt2tbN46uNA+A+f4z5xq4RlgUrvxCn8oSGTVuAb6H5XP4C5YFzK6gUy5KiH5Cj4luZp21jZNX9qjJwpenHn4Kue6wj3cHhrgmdAh2Du3s9CNNvMkNNtDR5DLcAY7Y9MB4Qanmz07DHoct6G2IY3Zeg8lwgLT5oGpdXrgie9+bbjsZSc6YygLAkjTQPJUyq81D0XPdhLiMed/V3L1i2UxZlD39+QM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
